### ISSUE TITLE
Missing isnothing() check in alloc_gmt18()

### ISSUE THREAD

**Issue by sutne** [mlhetland/Allocations.jl#1]
When `j` is `nothing`, allocation fails due to error: "cannot compare `nothing` with `<=`".

https://github.com/mlhetland/Allocations.jl/blob/1fd3de6cd3b7308dcff5241fb700bbfd42834488/src/algorithms.jl#L730-L733

Can be solved by changing line 733 to: 
```Julia
if isnothing(j) || j <= n return nothing end
```

**Comment by zootos** [comment]
Fixed in 4df121a517147054b77c0472ffde963b335c4a91
